<?php

namespace CLADevs\VanillaX\blocks\block\redstone;

use pocketmine\block\Block;
use pocketmine\block\BlockBreakInfo;
use pocketmine\block\BlockIdentifier;
use pocketmine\block\BlockLegacyIds;
use pocketmine\block\Transparent;
use pocketmine\item\Item;
use pocketmine\math\Vector3;
use pocketmine\player\Player;
use pocketmine\world\BlockTransaction;

class ObserverBlock extends Transparent{

    public function __construct(){
        parent::__construct(new BlockIdentifier(BlockLegacyIds::OBSERVER, 0), "Observer", new BlockBreakInfo(3.5));
    }

    public function place(BlockTransaction $tx, Item $item, Block $blockReplace, Block $blockClicked, int $face, Vector3 $clickVector, ?Player $player = null): bool{
//        $faces = [
//            Facing::DOWN => 0,
//            Facing::UP => 1,
//            Facing::NORTH => 2,
//            Facing::SOUTH => 3,
//            Facing::WEST => 4,
//            Facing::EAST => 5
//        ];
//        if(($facing = $faces[$face] ?? null) === null){
//            return false;
//        }
//        $this->facing = $facing;
        //TODO facing
        return parent::place($tx, $item, $blockReplace, $blockClicked, $face, $clickVector, $player); // TODO: Change the autogenerated stub
    }
}