<?php

namespace CLADevs\VanillaX\items\types;

use pocketmine\block\Block;
use pocketmine\item\Item;
use pocketmine\item\ItemIdentifier;
use pocketmine\item\ItemIds;
use pocketmine\item\ItemUseResult;
use pocketmine\math\Vector3;
use pocketmine\player\Player;

class FireChargeItem extends Item{

    public function __construct(){
        parent::__construct(new ItemIdentifier(ItemIds::FIRE_CHARGE, 0), "Fire Charge");
    }

    public function onInteractBlock(Player $player, Block $blockReplace, Block $blockClicked, int $face, Vector3 $clickVector): ItemUseResult{
        //        if($blockReplace->getId() === BlockLegacyIds::AIR){
        //            $player->getLevel()->setBlock($blockReplace, BlockFactory::get(BlockLegacyIds::FIRE), true, true);
        //            Session::playSound($player, "mob.blaze.shoot");
        //            if($player->isSurvival() || $player->isAdventure()) $this->pop();
        //        }
        //        return true;
        return parent::onInteractBlock($player, $blockReplace, $blockClicked, $face, $clickVector); // TODO: Change the autogenerated stub
    }
}