<?php

namespace CLADevs\VanillaX\items\types;

use CLADevs\VanillaX\entities\projectile\TridentEntity;
use CLADevs\VanillaX\session\Session;
use pocketmine\entity\Entity;
use pocketmine\entity\Location;
use pocketmine\item\Durable;
use pocketmine\item\ItemIdentifier;
use pocketmine\item\ItemIds;
use pocketmine\item\ItemUseResult;
use pocketmine\player\Player;

class TridentItem extends Durable{

    public function __construct(){
        parent::__construct(new ItemIdentifier(ItemIds::TRIDENT, 0), "Trident");
    }

    public function onReleaseUsing(Player $player): ItemUseResult{
//        if(!$this->hasEnchantment(Enchantment::RIPTIDE)){
//            $this->spawnTride($player);
//        }
        return parent::onReleaseUsing($player); // TODO: Change the autogenerated stub
    }

    public function spawnTride(Player $player): void{
        $this->applyDamage(1);
        $location = $player->getLocation();
        $location->y += $player->getEyeHeight();
        $location->yaw = ($location->getYaw() > 180 ? 360 : 0) - $location->getYaw();
        $location->pitch = -$location->getPitch();

        $diff = $player->getItemUseDuration();
        $p = $diff / 20;
        $baseForce = min((($p ** 2) + $p * 2) / 2, 1);
        $entity = new TridentEntity($location, $player);
        $entity->setMotion($player->getDirectionVector());
        $entity->setParent(clone $this);
        $entity->setOwningEntity($player);
        $entity->setMotion($entity->getMotion()->multiply($baseForce * 2));
        $entity->spawnToAll();
        Session::playSound($player, "item.trident.throw");
        $this->pop();
        $player->getInventory()->setItemInHand($this);
    }

    public function getMaxStackSize(): int{
        return 1;
    }

    public function getMaxDurability(): int{
        return 250;
    }
}